---
name: Lint

on: # yamllint disable-line
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**"
      - "**.yaml"
      - "**.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Run yamllint
        run: pip3 install yamllint --quiet && yamllint .

      - name: Run ansible-lint
        run: pip3 install ansible-lint ansible --quiet && ansible-lint
